services:
  db:
    image: postgres:15
    container_name: contacthub-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contacthub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
