spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacthub
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
